// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdTGl-6HSCr7S8En2DMJR_c1yNoXiYQM',
    appId: '1:788861249127:web:c0c163684c41714b6856c2',
    messagingSenderId: '788861249127',
    projectId: 'kenner-632d0',
    authDomain: 'kenner-632d0.firebaseapp.com',
    storageBucket: 'kenner-632d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTP5AADQ60ukeK_oXCv20UMDwkMjH5Ko',
    appId: '1:788861249127:android:20bd4715cd5f3f066856c2',
    messagingSenderId: '788861249127',
    projectId: 'kenner-632d0',
    storageBucket: 'kenner-632d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVi-kI8wLJ_NnTCq0zN9dwgN7mepg3Mak',
    appId: '1:788861249127:ios:a21671e483114c316856c2',
    messagingSenderId: '788861249127',
    projectId: 'kenner-632d0',
    storageBucket: 'kenner-632d0.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVi-kI8wLJ_NnTCq0zN9dwgN7mepg3Mak',
    appId: '1:788861249127:ios:2cea3bca350c38886856c2',
    messagingSenderId: '788861249127',
    projectId: 'kenner-632d0',
    storageBucket: 'kenner-632d0.appspot.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
